backend:
  name: github
  repo: 你的GitHub用户名/你的仓库名  # 请替换为你的真实仓库
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "downloadcode"
    label: "下载码"
    files:
      - file: "code.json"
        label: "下载码"
        name: "code"
        fields:
          - { label: "下载码", name: "value", widget: "string" } 